integration t: Reload test page during test_01_hw init
Loading of the testing_page added due to Firefox reporting
ReferenceError: can't access lexical declaration 'unX' before
initialization patchWindow.js line 60 > Function:199:7.

The error is not reproducible in browser without selenium. The error is
not there during browser.jsr_level setter. The error only appears during
the test initialization in start.py during pytest.main. The error goes
away after page reload.